name: Deploy Images to GHCR

on:
  push:
  pull_request:
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and export
        uses: docker/build-push-action@v4
        with:
          push: false
          context: ./src
          tags: tonylea/devcontainer-terraform:latest
          outputs: type=docker,dest=/tmp/devcontainer-terraform.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: image
          path: /tmp/devcontainer-terraform.tar

  # deploy:
  #   # this job will only run if the PR has been merged
  #   if: github.event.pull_request.merged == true
  #   runs-on: ubuntu-latest
  #   defaults:
  #     run:
  #       working-directory: "./src"
  #   steps:
  #     - name: "Checkout GitHub Action"
  #       uses: actions/checkout@main

  #     - name: "Login to GitHub Container Registry"
  #       uses: docker/login-action@v1
  #       with:
  #         registry: ghcr.io
  #         username: ${{github.actor}}
  #         password: ${{secrets.GITHUB_TOKEN}}

  #     - name: "Build Inventory Image"
  #       run: |
  #         docker push tonylea/devcontainer-terraform:latest

  #     - uses: actions/checkout@v2
  #     - name: Configure committer
  #       run: |
  #         git config user.name "GitHub Actions Bot"
  #         git config user.email "gitbot@fakeemail.com"

  #     - name: "Update version"
  #       run: |
  #         npm install -g standard-version
  #         standard-version
  #         git push --follow-tags origin HEAD:main

  #     - name: Build the Docker image
  #       run: |
  #         docker tag tonylea/devcontainer-terraform:latest tonylea/devcontainer-terraform::${{github.ref_name}}
  #         docker push tonylea/devcontainer-terraform:${{github.ref_name}}
